name: Build
on:
  push:
    branches: 
      - "*"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install libglfw3 libglfw3-dev cmake
      - name: set TERM variable
        run: export TERM=xterm
      - name: build
        run: make
